version: 2

jobs:
  build:
    working_directory: /go/src/github.com/gudtech/go-monetdb
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run: go test -v -race ./...
